accent = "#33ccff"
cursor = "#33ccff"
foreground = "#c0d0e8"
background = "#0a0b10"
selection_foreground = "#0a0b10"
selection_background = "#33ccff"

color0 = "#1a1b26"
color1 = "#ff6e8a"
color2 = "#00ff99"
color3 = "#ffcc66"
color4 = "#33ccff"
color5 = "#b48ead"
color6 = "#00e4cc"
color7 = "#a9b8d0"
color8 = "#3b4261"
color9 = "#ff8fa3"
color10 = "#33ffaa"
color11 = "#ffd788"
color12 = "#58e1ff"
color13 = "#c9a0dc"
color14 = "#33f5dd"
color15 = "#d8e0f0"
