$activeBorderColor = rgb(33ccff)

general {
    col.active_border = $activeBorderColor
}

group {
    col.border_active = $activeBorderColor
}

decoration {
    active_opacity = 0.70
    inactive_opacity = 0.45

    blur {
        enabled = true
        size = 8
        passes = 3
        new_optimizations = true
        xray = false
    }
}
